.TH "Racional.h" 3 "Martes, 20 de Octubre de 2020" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Racional.h \- Fichero cabecera del TDA \fBRacional\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBRacional\fP"
.br
.RI "T\&.D\&.A\&. \fBRacional\fP\&. "
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBgetMaxComDiv\fP (int primero, int segundo)"
.br
.RI "función que calcula el máximo comun divisor de dos números basado en el algo\&. de Euclides "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBRacional\fP\&. 


.PP
\fBAutor\fP
.RS 4
[Modificado por Salva Romero, proporcionado por profesor] 
.RE
.PP

.SH "Documentación de las funciones"
.PP 
.SS "int getMaxComDiv (int primero, int segundo)"

.PP
función que calcula el máximo comun divisor de dos números basado en el algo\&. de Euclides 
.PP
\fBParámetros\fP
.RS 4
\fIprimero\fP el primero de la pareja de números sobre la que se calcula 
.br
\fIsegundo\fP el segundo de la pareja de números sobre la que se calcula 
.RE
.PP
\fBDevuelve\fP
.RS 4
el MCD de ambos números 
.RE
.PP

.PP
Hace referencia a getMaxComDiv()\&.
.PP
Referenciado por getMaxComDiv() y Racional::reducir()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseRacional del código fuente\&.
